name = "uvm_r_ladder_dac"
top = "ams_top"
prefix = "Vams_top"
uvm = true
driver = "uvm"

verilog = [
    "verilog/r_ladder_dac_if.sv",
    "verilog/r_ladder_dac_dut.sv",
    "tb/r_ladder_dac_pkg/r_ladder_dac_pkg.sv",
    "verilog/ams_top.sv",
    "tb/r_ladder_dac_test.sv",
]

config = "config.yaml"

verilator_args = [
    "--trace",
    "--assert",
    "--timing",
    "+define+UVM_NO_DPI",
    "+incdir+tb/r_ladder_dac_pkg",
]
